import { Component } from '@angular/core';

@Component({
  selector: 'app-areas-activity',
  templateUrl: './areas-activity.component.html',
  styleUrls: ['./areas-activity.component.css']
})
export class AreasActivityComponent {
  expertises = [
    { title: "Direito Civil", path: "../../../assets/images/Rectangle 3.png", text: "O escritório Adir Machado Advogados Associados é especializado na área de Direito Civil, abrangendo diversas questões legais relacionadas a relações entre particulares. Seus serviços incluem a consultoria na elaboração, análise e negociação de contratos civis, garantindo conformidade com a legislação vigente. Além disso, representam clientes em casos de responsabilidade civil, incluindo danos materiais e morais, buscando reparação e indenização. O escritório também oferece assistência em questões relacionadas a obrigações contratuais e legais, como cumprimento de acordos e dívidas. Na área de sucessões, eles fornecem orientação em casos de herança, testamentos e partilhas de bens para garantir uma transferência de patrimônio adequada. Além disso, atuam em casos que envolvem propriedade, posse e outros direitos relacionados a bens móveis e imóveis, bem como em questões de direito de família, como divórcios, guarda de filhos, pensão alimentícia e sucessões. Em situações de danos morais e materiais causados por terceiros, o escritório defende seus clientes em busca de indenizações adequadas. A expertise do escritório no campo do Direito Civil se destaca por sua capacidade de fornecer orientação legal precisa e representação eficaz para proteger os interesses dos clientes em uma ampla gama de questões civis." },
    { title: "Direito Público", path: "../../../assets/images/Rectangle 5.png", text: "O escritório Adir Machado Advogados Associados se destaca na área de Direito Público, oferecendo serviços especializados que abrangem uma ampla gama de questões governamentais e administrativas. Sua atuação compreende a assessoria em Direito Administrativo, representação em processos administrativos, ações judiciais contra o Estado, consultoria em Direito Constitucional, advocacia eleitoral, assessoria em contratos públicos, defesas em casos de improbidade administrativa e acompanhamento de processos perante os Tribunais de Contas. Além disso, o escritório oferece serviços personalizados, adaptando-se às necessidades específicas de cada cliente na esfera do Direito Público. Seu compromisso é fornecer soluções jurídicas eficazes, sempre visando à defesa dos interesses dos clientes no âmbito público." },
    { title: "Direito Empresarial", path: "../../../assets/images/Rectangle 7.png", text: "A área de atuação \"Direito Empresarial\" do escritório Adir Machado Advogados Associados oferece uma gama abrangente de serviços legais voltados para empresas. Com especialização nesse campo, o escritório presta assessoria na elaboração, revisão e negociação de contratos comerciais, fusões e aquisições, além de oferecer consultoria em questões societárias, como formação de empresas, reestruturação societária e governança corporativa. Além disso, eles representam seus clientes em litígios empresariais, resolvendo disputas comerciais por meio de negociações ou processos judiciais quando necessário. Com uma abordagem personalizada, o escritório busca proteger os interesses e promover o sucesso das empresas que atende, fornecendo soluções jurídicas eficazes e estratégicas no campo do Direito Empresarial." },
    { title: "Direito Tributário", path: "../../../assets/images/Rectangle 9.png", text: "A área de atuação \"Direito Tributário\" do escritório Adir Machado Advogados Associados é especializada em questões fiscais e tributárias. O escritório presta consultoria e representação em assuntos relacionados à legislação tributária, ajudando empresas e indivíduos a entender e cumprir suas obrigações fiscais de maneira eficiente e em conformidade com a lei. Isso inclui a análise de planejamento tributário, a revisão de impostos e contribuições, a defesa em disputas fiscais e a busca por soluções para minimizar a carga tributária. A equipe jurídica do escritório está comprometida em fornecer orientação estratégica e representação eficaz para seus clientes, visando otimizar sua situação fiscal e proteger seus interesses no campo do Direito Tributário." },
    { title: "Direito do Consumidor", path: "../../../assets/images/Rectangle 5.png", text: "A área de atuação \"Direito do Consumidor\" no escritório Adir Machado Advogados Associados é focada em proteger os direitos e interesses dos consumidores. Com expertise nesse campo, o escritório presta assessoria em casos que envolvem relações de consumo, tais como reclamações sobre produtos ou serviços defeituosos, práticas comerciais desleais, contratos de consumo e responsabilidade do fornecedor. Além disso, representam consumidores em litígios e buscam compensações por danos materiais ou morais decorrentes de violações ao Direito do Consumidor. O escritório se empenha em assegurar que seus clientes recebam o tratamento justo e legal ao lidar com questões relacionadas ao consumo, fornecendo orientação especializada e representação eficaz nesse campo específico do Direito." },
    { title: "Direito Registral, Notarial e Imobiliário" , path: "../../../assets/images/Rectangle 5.png", text: "A área de atuação \"Direito Registral, Notarial e Imobiliário\" no escritório Adir Machado Advogados Associados se concentra em questões relacionadas a registros, documentação notarial e transações imobiliárias. Com expertise nesse campo, o escritório oferece assistência em processos de registro de propriedade, elaboração e análise de contratos imobiliários, como compra e venda, locações e financiamentos. Além disso, eles auxiliam na resolução de disputas envolvendo propriedades, garantindo que os interesses de seus clientes sejam protegidos em questões como desapropriações, regularização fundiária e litígios imobiliários. A equipe jurídica do escritório está empenhada em fornecer orientação especializada e representação eficaz no campo do Direito Registral, Notarial e Imobiliário, assegurando que as transações e propriedades de seus clientes estejam em conformidade com a legislação e seus direitos devidamente protegidos." },
    
  ];
}
