import { Component } from '@angular/core';

@Component({
  selector: 'app-team-view',
  templateUrl: './team-view.component.html',
  styleUrls: ['./team-view.component.css']
})
export class TeamViewComponent {
  lawyers = [
    { name: "Dr. Adir Machado Bandeira", title: "Advogado", path: "../../../assets/images/img_9773.jpg", desc: "O Dr. Adir Machado Bandeira é um renomado professor e advogado que possui uma trajetória exemplar no campo jurídico. Completando 25 anos de advocacia em 31/05/2024, ele é um profissional admirado por sua origem humilde, inteligência aguçada e habilidades notáveis na oratória, dominando a técnica jurídica com maestria.\n\nDesde o início de sua carreira, sempre se destacou por sua ética inabalável, sobriedade e firmeza no exercício da advocacia. Seu compromisso intransigente em defender os interesses de seus clientes e sua combatividade incansável fazem dele um verdadeiro defensor da justiça.\n\nAlém disso, o Dr. Adir Machado é amplamente reconhecido por seu apurado conhecimento em Direito Público. Ao longo de sua trajetória, ele desempenhou diversos cargos públicos de relevo, onde sempre se destacou por sua vasta bagagem jurídica e pela firmeza de seus propósitos. Sua atuação na Administração Pública, seja no Poder Executivo ou no Legislativo, permitiu-lhe compreender profundamente as nuances do Direito Público e desenvolver uma expertise notável nessa área.\n\nÉ uma referência quando se trata de defesa dos direitos dos cidadãos e do Estado. Seu conhecimento jurídico abrangente e sua habilidade em aplicar a legislação de forma estratégica tornam-no um advogado altamente respeitado e confiável.\nAo longo de sua carreira, construiu uma reputação sólida e duradoura, tanto entre seus colegas advogados quanto entre seus clientes. Sua dedicação incansável, profissionalismo e comprometimento em fornecer um serviço jurídico de qualidade são marcas registradas de sua atuação.\n\nNeste marco de 25 anos de advocacia, o Dr. Adir Machado Bandeira celebra uma carreira repleta de sucessos e conquistas. Seu legado é marcado por sua competência, conhecimento e o compromisso inabalável de buscar a justiça para seus clientes.\n\nEm resumo, o Dr. Adir Machado Bandeira é um professor e advogado exemplar, cuja trajetória de 25 anos de advocacia é marcada por sua origem humilde, inteligência, oratória persuasiva, domínio técnico-jurídico, ética, sobriedade, firmeza e combatividade na defesa de seus clientes. Seu profundo conhecimento em Direito Público, aliado à sua atuação destacada em diversos cargos públicos, o posiciona como um verdadeiro especialista nessa área. Sua dedicação e competência são pilares de sua carreira e o fazem um profissional respeitado e admirado em seu campo de atuação." },
    { name: "Dra. Aridênia Moura Santos", title: "Advogada", path: "../../../assets/images/img_9973.jpg", desc:"Aridênia Moura Santos é uma figura essencial no escritório Adir Machado advogados associados. Além de sua expertise em questões relacionadas a licitações, execuções e defesa de servidores públicos, ela desempenha um papel primordial como gestora do escritório, assumindo a posição de CEO. Sua atuação é fundamental para a administração e organização eficiente de todas as atividades do escritório.\n\nCom sua experiência oriunda de cartório, Aridênia traz consigo um conhecimento valioso sobre os procedimentos administrativos e burocráticos necessários no âmbito do escritório de advocacia. Sua familiaridade com a gestão de documentos, prazos e contatos com órgãos públicos e fornecedores agrega um diferencial significativo para o escritório.\n\nComo gestora, é responsável por estabelecer e manter relacionamentos sólidos com os clientes, fornecedores e parceiros do escritório. Ela é a principal responsável pelos contatos comerciais e administrativos, garantindo uma comunicação afável, acolhedora e eficiente em todas as interações.\n\nAlém disso, desempenha um papel fundamental na coordenação das equipes do escritório, garantindo que todas as tarefas sejam executadas de forma adequada e dentro dos prazos estabelecidos. Sua capacidade de organização e gerenciamento contribui para a eficiência e o bom funcionamento das atividades diárias do escritório.\n\nAridênia também desempenha um papel crucial na representação administrativa do escritório, atuando como porta-voz em questões administrativas e estratégicas. Sua liderança e habilidades de negociação permitem que ela defenda os interesses do escritório de forma eficaz e proativa.\n\nEm resumo, Aridênia Moura Santos é uma peça fundamental no escritório. Sua vasta experiência oriunda de cartório, aliada à sua função como gestora e CEO do escritório, garante que todas as atividades administrativas sejam realizadas de forma eficiente e que os clientes recebam um atendimento profissional e de alta qualidade. Sua liderança e habilidades organizacionais contribuem para o sucesso e a excelência do escritório como um todo." },
    { name: "Dr. Fellipe Moura de Britto", title: "Advogado", path: "../../../assets/images/img_9813.jpg", desc:"O escritório Adir Machado advogados associados tem a satisfação de contar com a presença do Dr. Fellipe Moura de Britto, um profissional altamente qualificado e experiente na área do Direito das Sucessões, com especialização em inventário e respectivos cálculos. Sua atuação nessa área específica traz um diferencial significativo para o escritório e para os clientes que buscam serviços advocatícios relacionados à sucessão patrimonial.\n\nO Dr. Fellipe Moura de Britto possui um conhecimento aprofundado nas complexidades e nuances do Direito das Sucessões, com destaque para o inventário, que é um procedimento legal necessário após o falecimento de uma pessoa, visando a regularização e partilha de seus bens entre os herdeiros.\n\nCom base em sua expertise, o Dr. Fellipe Moura de Britto oferece serviços especializados no processo de inventário, auxiliando os clientes em todas as etapas do procedimento. Ele possui uma visão abrangente e detalhada sobre os requisitos legais, prazos, documentação necessária, além de conhecer as melhores estratégias para alcançar uma partilha justa e eficiente dos bens envolvidos.\n\nAlém disso, o Dr. Fellipe Moura de Britto tem experiência em realizar cálculos relacionados ao inventário, como a apuração e a valoração dos bens, dívidas, direitos e obrigações dos envolvidos. Esses cálculos são fundamentais para determinar a correta distribuição do patrimônio e evitar conflitos futuros.\n\nCom sua abordagem profissional e comprometimento com a excelência, o Dr. Fellipe Moura de Britto trabalha em estreita colaboração com os clientes, compreendendo suas necessidades e objetivos específicos. Ele se dedica a fornecer um serviço personalizado, orientando-os de forma clara e transparente durante todo o processo de inventário, visando garantir que seus direitos sejam preservados.\n\nDessa forma, o escritório do advogado Adir Machado Bandeira, por meio do Dr. Fellipe Moura de Britto, oferece serviços especializados em Direito das Sucessões, com foco no inventário e respectivos cálculos. Os clientes podem contar com um profissional experiente e comprometido em oferecer uma representação jurídica de qualidade, visando a efetiva e justa divisão do patrimônio entre os herdeiros envolvidos." },
  ];
}
